public enum Ingredienti {
    ALICI, BASILICO, BELLE_DONNE, CAPPERI, CARCIOFI, COTTO, CRUDO, FUNGHI, GALANTERIA, GEMME_DELL_INFINITO, GORGONZOLA, MOZZARELLA, MOZZARELLA_DI_BUFALA, OLIVE_NERE, ONNIPOTENZA, ORIGANO, PANNA, PATATINE, PEPERONI, POMODORINI, POMODORO, RUCOLA, SALAME_PICCANTE, SALSICCIA, SPECK, WURSTEL;
}
